### ISSUE TITLE
Exception after installation

### ISSUE THREAD

**Issue by gri3li** [jiisoft/jii#22]
Throws an exception:
```
TypeError: Cannot read property 'ClassLoader' of undefined
    at Object.<anonymous> (C:\Users\gri3li\PhpstormProjects\jii-test\node_modules\jii\app.js:97:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\gri3li\PhpstormProjects\jii-test\app.js:1:73)
    at Module._compile (module.js:570:32)`
```

File app.js contains only:
```javascript
var Jii = require('jii');
```

**Comment by affka** [comment]
Исправлено в 1.0.3.
Сейчас весь код фреймворка мигрирует с Neatness классов, на es6 классы. Поэтому его какое-то время еще будет колбасить.
